trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

steps:
- checkout: self

- task: UseDotNet@2
  displayName: 'Setup .NET 7'
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

- script: 'dotnet workload install maui --ignore-failed-sources'
  displayName: 'Install MAUI Workload'

- script: 'dotnet restore L00177804_Project/L00177804_Project.csproj'
  displayName: 'Restore Dependencies'

- script: 'dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-android --no-restore'
  displayName: 'Build MAUI Android'

- script: 'dotnet test --no-build --verbosity normal'
  displayName: 'Run tests'

- script: 'echo "Deploying to Azure App Service"'
  displayName: 'Display message'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))

- task: UseDotNet@2
  displayName: 'Setup .NET 7'
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

- script: 'dotnet workload install maui --ignore-failed-sources'
  displayName: 'Install MAUI Workload'

- script: 'dotnet restore L00177804_Project/L00177804_Project.csproj'
  displayName: 'Restore Dependencies'

- script: 'dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-ios --no-restore'
  displayName: 'Build MAUI iOS'

- script: 'dotnet test --no-build --verbosity normal'
  displayName: 'Run tests'

- script: 'echo "Deploying to Azure App Service"'
  displayName: 'Display message'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
