name: "CodeQL"

on:
  workflow_dispatch:

jobs:
  analyze:
    name: analyze
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          ./bin
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/project.assets.json') }}-${{ matrix.language }}
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - run: dotnet workload install maui --ignore-failed-sources
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Build project
      run: dotnet build 
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
