name: "CodeQL"

on:
  workflow_dispatch:

jobs:
  analyze:
    name: analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
    - name: Build project
      run: dotnet build L00177804_Project/L00177804_Project.csproj
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
