name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
        with:
          dotnet-version: 7.0.x
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore L00177804_Project/L00177804_Project.csproj

      - name: Build MAUI Android
        run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-android --no-restore

      - name: .NET Lint
        uses: zyactions/dotnet-lint@v1
        with:
          workspace: L00177804_Project/L00177804_Project.csproj
          implicit-restore: true

          # xunit test build for android
      - name: Build xUnit Tests
        run: dotnet build L00177804_Project/xUnitTest.csproj -c Release -f net7.0-android --no-restore /p:RunAndroidUnitTests=True



# MAUI iOS Build
  build-ios:
    runs-on: macos-12
    name: iOS Build
    steps:

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore L00177804_Project/L00177804_Project.csproj

      - name: Build MAUI iOS
        run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: .NET Lint
        uses: zyactions/dotnet-lint@v1
        with:
          workspace: L00177804_Project/L00177804_Project.csproj
          implicit-restore: true

          # xunit test build for ios
      - name: Build xUnit Tests
        run: dotnet build L00177804_Project/xUnitTest.csproj -c Release -f net7.0-ios --no-restore /p:RuniOSUnitTests=True /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
