
# Name of the Github Actions workflow
name: MAUI
# Define the events that trigger the Github Actions workflow
on:
  push:
    branches:
      - master # Only trigger the workflow on the master branch
    paths-ignore:
      - '**/*.md' # Ignore markdown files
      - '**/*.git*' # Ignore git files
  pull_request:
    branches:
      - master # Only trigger the workflow on the master branch
  workflow_dispatch:

# Define the environment variables to be used in the Github Actions workflow
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true


jobs:
  # Setup job to install .NET and MAUI workload
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted]
        dotnet-version: [7.0.x]
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v3
        with:
          # Cache NuGet packages for faster builds
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/unwanted
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - run: dotnet workload install maui --ignore-failed-sources
  
  # Build job to build the MAUI app for Android
  build-android:
    # Define the jobs that this job depends on
    needs: [setup]
    name: Build MAUI for Android
    runs-on: self-hosted
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        dotnet-version: [7.0.x]
        target-framework: [net7.0-android]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet build L00177804_Project/L00177804_Project.csproj -f ${{ matrix.target-framework }}
      
 # Build job to build the MAUI app for iOS
  build-ios:
    # Define the jobs that this job depends on
    needs: [setup]
    name: Build MAUI for iOS
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        dotnet-version: [7.0.x]
        target-framework: [net7.0-ios]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet build L00177804_Project/L00177804_Project.csproj -f ${{ matrix.target-framework }}
    
  # Publish job to publish the MAUI app artifacts
  publish:
    needs: [build-android, build-ios]
    name: Publish MAUI App Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Maui-artifact
          path: |
            L00177804_Project/bin/Release/net7.0-android/
            L00177804_Project/bin/Release/net7.0-ios/

  # Test job to test the MAUI app
  test:
    needs: [build-android, build-ios]
    name: Test MAUI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet test --no-build --verbosity normal
      
  # Deploy job to deploy the MAUI app         
  deploy:
    needs: [publish]
    name: Deploy MAUI App
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Playstore
        run: echo "Deploying to Playstore in progress"
            
      
    
