
name: MAUI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.git*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-android:
    name: Build MAUI for Android
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
      - uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/unwanted
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
      - name: Restore Dependencies
        run: dotnet restore L00177804_Project/L00177804_Project.csproj
      - name: Build MAUI Android
        run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-android --no-restore
      - name: Run tests for Android
        run: dotnet test --no-build --verbosity normal
      - name: Publish artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MAUI-Android-artifacts
          path: L00177804_Project/bin/Release/net7.0-android/

  build-ios:
    name: Build MAUI for iOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Cache
      - uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            !~/.nuget/packages/unwanted
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
      - name: Restore Dependencies
        run: dotnet restore L00177804_Project/L00177804_Project.csproj
      - name: Build MAUI iOS
        run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-ios --no-restore
      - name: Run tests for iOS
        run: dotnet test --no-build --verbosity normal
      - name: Publish artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MAUI-iOS-artifacts
          path: L00177804_Project/bin/Release/net7.0-ios/
