    name: CI Build

    on:
      push:
        branches: [ master ]
        paths-ignore:
          - '**/*.md'
          - '**/*.gitignore'
          - '**/*.gitattributes'
      pull_request:
        branches: [ master ]
      workflow_dispatch:
    
    permissions:
      contents: read
    
    env:
      DOTNET_NOLOGO: true                     # Disable the .NET logo
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
      DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
    
    jobs:
    # MAUI Android Build
      Build-Test-android:
        runs-on: windows-latest
        name: Android Build and Test
        steps:
    
          - name: Checkout
            uses: actions/checkout@v3
    
          - name: Setup .NET 7
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 7.0.x
              
          - name: Install MAUI Workload
            run: dotnet workload install maui --ignore-failed-sources
    
          - name: Restore Dependencies
            run: dotnet restore L00177804_Project/L00177804_Project.csproj
    
          - name: Build MAUI Android
            run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-android --no-restore
              # xunit test build for android
          - name: Run tests
            run: dotnet test --no-build --verbosity normal

      deploy-android:
        needs: [Build-Test-android]
        runs-on: windows-latest
        # display output message
        steps:
          - name: Display message
            run: echo "Deploying to Azure App Service"

    # MAUI iOS Build
      Build-Test-ios:
        runs-on: macos-12
        name: iOS Build and Test
        steps:
    
          - name: Checkout
            uses: actions/checkout@v3
    
          - name: Setup .NET 7
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: 7.0.x
    
          - name: Install MAUI Workload
            run: dotnet workload install maui --ignore-failed-sources
    
          - name: Restore Dependencies
            run: dotnet restore L00177804_Project/L00177804_Project.csproj
    
          - name: Build MAUI iOS
            run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f net7.0-ios --no-restore
              # xunit test build for ios
          - name: Run tests
            run: dotnet test --no-build --verbosity normal

      Deploy-ios:
        needs: [Build-Test-ios]
        runs-on: windows-latest
        # display output message
        steps:
          - name: Display message
            run: echo "Deploying to Azure App Service"

 
      xUnitTests:
        runs-on: windows-latest
        name: xUnit Test
        steps:
                 
          - name: Install MAUI Workload
            run: dotnet workload install maui --ignore-failed-sources
    
          - name: Restore Dependencies
            run: dotnet restore xUnitTests/xUnitTests.csproj

              # xunit test build for android
          - name: Run tests
            run: dotnet test --no-build --verbosity normal
