name: CI Build

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  PROJECT_NAME: L00177804_Project
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Switch to a Linux-based runner
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
        target-framework: [net7.0-android, net7.0-ios]
    name: Build and Test ${{ matrix.os }} ${{ matrix.target-framework }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sonar Scan
        # You may pin to the exact commit or the version.
        # uses: sijomc/sonarscan-action@5a3a0c0eacbe76ac7c3e3513696f7449f4f914a5
        uses: sijomc/sonarscan-action@1.1

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget
          key: nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

      - name: Build MAUI
        run: dotnet build ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj -c Release -f ${{ matrix.target-framework }} --no-restore
