
# Name of the Github Actions workflow
name: MAUI CI/CD
# Define the events that trigger the Github Actions workflow
on:
  push:
    branches:
      - master # Only trigger the workflow on the master branch
    paths-ignore:
      - '**/*.md' # Ignore markdown files
      - '**/*.git*' # Ignore git files
  pull_request:
    branches:
      - master # Only trigger the workflow on the master branch
  workflow_dispatch:

# Define the environment variables to be used in the Github Actions workflow
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true


jobs:
  # Setup job to install .NET and MAUI workload
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted]
        dotnet-version: [7.0.x]
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # Install the MAUI workload
      - run: dotnet workload install maui --ignore-failed-sources
  
  # Build job to build the MAUI app for Android
  build-android:
    # Define the jobs that this job depends on
    needs: [setup]
    name: Build MAUI for Android
    runs-on: self-hosted
    strategy:
      matrix:
        os: [android-latest]
        dotnet-version: [7.0.x]
        target-framework: [net7.0-android]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f ${{ matrix.target-framework }}
      
      - name: Create Android artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MAUI-Android-artifacts
          path: L00177804_Project/bin/Release/net7.0-android/
      
 # Build job to build the MAUI app for iOS
  build-ios:
    # Define the jobs that this job depends on
    needs: [setup]
    name: Build MAUI for iOS
    runs-on: self-hosted
    strategy:
      matrix:
        os: [macos-latest]
        dotnet-version: [7.0.x]
        target-framework: [net7.0-ios]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet build L00177804_Project/L00177804_Project.csproj -c Release -f ${{ matrix.target-framework }}

      - name: Create IOS artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MAUI-iOS-artifacts
          path: L00177804_Project/bin/Release/net7.0-ios/
    

  # Test job to test the MAUI app
  test:
    needs: [build-android, build-ios]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore NuGet packages
        run: dotnet restore
        working-directory: ./xUnitTests
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ./xUnitTests
      - name: Run tests
        run: dotnet test xUnitTests/xUnitTests.csproj
        #run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.xml" ./xUnitTests
      #- name: Publish Test Results
      #  uses: EnricoMi/publish-unit-test-result-action@v2.7.0
      #  with:
      #    files: |
      #      **/test_results.xml

  # Deploy job to deploy the MAUI app         
  deploy:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    name: Deploy MAUI App
    runs-on: self-hosted
    steps:
      - name: Deploy to Playstore
        run: echo "Deploying to Playstore in progress"
  
            
      
    
