name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/xUnitTests.csproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-
          ${{ runner.os }}-
          ${{ runner.os }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: dotnet test --configuration Release --no-restore

