name: Testing

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.git*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        dotnet-version: [7.0.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.2.1
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/L00177804_Project.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet workload install maui --ignore-failed-sources

  test-build-artifacts:
    needs: [setup]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2.2.1
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/L00177804_Project.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore NuGet packages
        run: dotnet restore
        working-directory: ./xUnitTests
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ./xUnitTests
      - name: Run tests
        run: dotnet test --logger:xunit
      - name: Create IOS artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MAUI-iOS-artifacts
          path: xUnitTests/bin/Release/net7.0-ios/
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            **/TestResults.xml
