###### CANT RUN UNTIL MINUTES ARE BACK ON GITHUB ACTIONS

# Name of the Github Actions workflow
name: Testing
# Define the events that trigger the Github Actions workflow
on:
#  push:
#    branches:
#      - master # Only trigger the workflow on the master branch
#    paths-ignore:
#      - '**/*.md' # Ignore markdown files
#      - '**/*.git*' # Ignore git files
#  pull_request:
#    branches:
#      - master # Only trigger the workflow on the master branch
  workflow_dispatch:

# Define the environment variables to be used in the Github Actions workflow
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true


jobs:
  # Setup job to install .NET and MAUI workload
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [unbuntu-latest]
        dotnet-version: [7.0.x]
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # Install the MAUI workload
      - run: dotnet workload install maui --ignore-failed-sources

  # Test job to test the MAUI app
  test:
    needs: [setup]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore NuGet packages
        run: dotnet restore
        working-directory: ./xUnitTests
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ./xUnitTests
      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.xml" ./xUnitTests
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        with:
          files: |
           **/test_results.xml